/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as InundationRouteImport } from './routes/inundation'
import { Route as RoadIntelligenceRouteImport } from './routes/road-intelligence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const InundationRoute = InundationRouteImport.update({
  id: '/inundation',
  path: '/inundation',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadIntelligenceRoute = RoadIntelligenceRouteImport.update({
  id: '/road-intelligence',
  path: '/road-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRoute
  '/inundation': typeof InundationRoute
  '/road-intelligence': typeof RoadIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRoute
  '/inundation': typeof InundationRoute
  '/road-intelligence': typeof RoadIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRoute
  '/inundation': typeof InundationRoute
  '/road-intelligence': typeof RoadIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authority' | '/inundation' | '/road-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authority' | '/inundation' | '/road-intelligence'
  id: '__root__' | '/' | '/authority' | '/inundation' | '/road-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorityRoute: typeof AuthorityRoute
  InundationRoute: typeof InundationRoute
  RoadIntelligenceRoute: typeof RoadIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inundation': {
      id: '/inundation'
      path: '/inundation'
      fullPath: '/inundation'
      preLoaderRoute: typeof InundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/road-intelligence': {
      id: '/road-intelligence'
      path: '/road-intelligence'
      fullPath: '/road-intelligence'
      preLoaderRoute: typeof RoadIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorityRoute: AuthorityRoute,
  InundationRoute: InundationRoute,
  RoadIntelligenceRoute: RoadIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
